SET MAX_MEMORY_ROWS 1000000;
SET CACHE_SIZE 262144;
SET DEFAULT_LOCK_TIMEOUT 60000;
;
CREATE SCHEMA IF NOT EXISTS FTL AUTHORIZATION SA;
CREATE FORCE ALIAS PUBLIC.FTL_DROP_INDEX FOR "com.apollocurrency.aplwallet.apl.db.FullTextTrigger.dropIndex";
CREATE FORCE ALIAS PUBLIC.FTL_SEARCH NOBUFFER FOR "com.apollocurrency.aplwallet.apl.db.FullTextTrigger.search";
CREATE FORCE ALIAS PUBLIC.FTL_CREATE_INDEX FOR "com.apollocurrency.aplwallet.apl.db.FullTextTrigger.createIndex";
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_EDD8D597_4F39_4017_9389_FA7A5C612999 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_9B7D3FF0_A608_4A62_A8A0_F43FDBB4565C START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_91787B50_FAC6_40E0_AE37_29DAA7913218 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_02FB98B3_12CC_4144_85DF_974ED1D2DBC9 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_9B3AE74B_E66D_4B93_84D5_1EF01A057E26 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.transaction_seq START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_B0838F08_B2A0_4ACC_B64D_7A8DBF112E8D START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_52579908_9D92_4A43_9A02_A8E092DC81E7 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_7DAE5796_5D08_4878_B93A_26EABA14BEEA START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_03B94F82_FD80_4D84_8CF0_A6F28DCD9CF1 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_AA49D29A_2B05_4B3E_BAF7_EF691491A36E START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_2EE8C924_F2E6_40F5_BB7C_142ECF11E3B0 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_51DABEF2_E173_4EF3_8D33_3D5F38711C92 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_59B00FDF_11A3_4A7F_A37A_4308091108E4 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_D35883BE_EEDB_4D28_8C21_FEF7B5843D22 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_54D3687D_B190_410C_AF6C_0A568995B8C6 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_B5CE36E2_88F6_4AEA_9BEE_51A9844B8921 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_87379CE4_8CD6_4EB3_AEBB_F1C23337272D START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_E0D63F78_469E_498A_B38D_CDF174A6EBE8 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_719D675E_E14D_4B7E_9EE7_F7783292A612 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_6FEACD8B_A449_4E4E_A341_8A33D0223BA7 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_1700B4D9_DFA3_4995_9E87_D534E607A9B5 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_C670A685_58B2_49C2_8E4C_C6D4F10AE4CD START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_81A85DFB_F28B_4884_9338_290DDA3DFE7B START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_E2FCA41B_6117_4C7E_9EF5_335C2F4A3F0A START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_704D5836_6E55_4915_87A1_83489B758FFA START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_0C38A777_74DE_450C_BF80_7679A8B1EB9C START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.block_seq START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_FB8293B0_4068_471F_8AA7_9F99DE361C91 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_0ECC3693_53EF_4260_87EE_462587450E46 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_718413A2_E908_474F_A271_CE6FA8B902BA START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_EAC05067_4987_4D7F_A42B_1A2135E7038C START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_043ABA9A_85EA_4BF4_9625_10C45E7923FD START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_84EDC395_10D8_4200_AF6E_B0986FAE40BC START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_D4541341_31D1_4A31_9D63_A61D37917069 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_4B14966A_B157_49F1_ADC6_4F20F363B47B START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_48C49157_56EB_4C58_8760_3A7F0AB8C474 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_4248AF3C_35F7_4E97_A4D3_2FCC738DD4F7 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_FA292EF3_DA05_400A_9853_E6D54ECC908E START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_FC56E1E9_7904_4931_BCFD_6A555F4F82FC START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.update_status_seq START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_685BB3A9_D6B2_48C7_BDB5_A742310CF13E START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_EE17D780_F458_4947_A843_B159E2E62EB3 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_D79BD2C8_34A5_43A9_AE4C_593CA197BCC4 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_6BE1A667_76F2_422B_AFB2_E87365DA6A28 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_F4ED3006_C280_4E5C_8FC5_82D0A197B626 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_22A879DE_118B_43ED_8BF0_A4D9E0E8361F START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_6AC14DF9_84FB_4296_A7EB_6F1F2A0F5730 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.ACCOUNT_SEQ START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_3F3CCF94_E2B9_497C_A7D7_86A88A541B23 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_E2FAB68A_8FA4_4B34_8A9D_49393328ACF9 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_8F0B3C14_9D25_4D6A_A966_A76CF0A5CA31 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_0E41089D_E736_4111_AF26_E421C68C9257 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_7F4860EF_5B61_48B9_850B_0CC5FFF4E6C3 START WITH 1 BELONGS_TO_TABLE;

-- 1 +/- SELECT COUNT(*) FROM PUBLIC.VERSION;
CREATE CACHED TABLE PUBLIC.BLOCK(
DB_ID BIGINT DEFAULT PUBLIC.block_seq.nextval NOT NULL,
ID BIGINT NOT NULL SELECTIVITY 100,
VERSION INT NOT NULL SELECTIVITY 1,
TIMESTAMP INT NOT NULL SELECTIVITY 100,
PREVIOUS_BLOCK_ID BIGINT SELECTIVITY 100,
TOTAL_AMOUNT BIGINT NOT NULL SELECTIVITY 1,
TOTAL_FEE BIGINT NOT NULL SELECTIVITY 1,
PAYLOAD_LENGTH INT NOT NULL SELECTIVITY 1,
PREVIOUS_BLOCK_HASH BINARY(32) SELECTIVITY 100,
CUMULATIVE_DIFFICULTY VARBINARY NOT NULL SELECTIVITY 100,
BASE_TARGET BIGINT NOT NULL SELECTIVITY 45,
NEXT_BLOCK_ID BIGINT SELECTIVITY 100,
HEIGHT INT NOT NULL SELECTIVITY 100,
GENERATION_SIGNATURE BINARY(64) NOT NULL SELECTIVITY 100,
BLOCK_SIGNATURE BINARY(64) NOT NULL SELECTIVITY 100,
PAYLOAD_HASH BINARY(32) NOT NULL SELECTIVITY 1,
GENERATOR_ID BIGINT NOT NULL SELECTIVITY 1
);
CREATE TABLE IF NOT EXISTS VERSION(
NEXT_UPDATE INT NOT NULL SELECTIVITY 100
);
ALTER TABLE PUBLIC.BLOCK ADD CONSTRAINT PUBLIC.CONSTRAINT_3 PRIMARY KEY(DB_ID);
-- 104833 +/- SELECT COUNT(*) FROM PUBLIC.BLOCK;
CREATE UNIQUE INDEX PUBLIC.BLOCK_ID_IDX ON PUBLIC.BLOCK(ID);
CREATE UNIQUE INDEX PUBLIC.BLOCK_HEIGHT_IDX ON PUBLIC.BLOCK(HEIGHT);
CREATE INDEX PUBLIC.BLOCK_GENERATOR_ID_IDX ON PUBLIC.BLOCK(GENERATOR_ID);
CREATE UNIQUE INDEX PUBLIC.BLOCK_TIMESTAMP_IDX ON PUBLIC.BLOCK(TIMESTAMP DESC);
CREATE CACHED TABLE PUBLIC.TRANSACTION(
DB_ID BIGINT DEFAULT PUBLIC.transaction_seq.nextval NOT NULL,
ID BIGINT NOT NULL SELECTIVITY 100,
DEADLINE SMALLINT NOT NULL SELECTIVITY 1,
RECIPIENT_ID BIGINT SELECTIVITY 2,
TRANSACTION_INDEX SMALLINT NOT NULL SELECTIVITY 8,
AMOUNT BIGINT NOT NULL SELECTIVITY 3,
FEE BIGINT NOT NULL SELECTIVITY 1,
FULL_HASH BINARY(32) NOT NULL SELECTIVITY 100,
HEIGHT INT NOT NULL SELECTIVITY 26,
BLOCK_ID BIGINT NOT NULL SELECTIVITY 26,
SIGNATURE BINARY(64) NOT NULL SELECTIVITY 100,
TIMESTAMP INT NOT NULL SELECTIVITY 91,
TYPE TINYINT NOT NULL SELECTIVITY 1,
SUBTYPE TINYINT NOT NULL SELECTIVITY 1,
SENDER_ID BIGINT NOT NULL SELECTIVITY 1,
BLOCK_TIMESTAMP INT NOT NULL SELECTIVITY 26,
REFERENCED_TRANSACTION_FULL_HASH BINARY(32) SELECTIVITY 1,
PHASED BOOLEAN DEFAULT FALSE NOT NULL SELECTIVITY 1,
ATTACHMENT_BYTES VARBINARY SELECTIVITY 4,
VERSION TINYINT NOT NULL SELECTIVITY 1,
HAS_MESSAGE BOOLEAN DEFAULT FALSE NOT NULL SELECTIVITY 1,
HAS_ENCRYPTED_MESSAGE BOOLEAN DEFAULT FALSE NOT NULL SELECTIVITY 1,
HAS_PUBLIC_KEY_ANNOUNCEMENT BOOLEAN DEFAULT FALSE NOT NULL SELECTIVITY 1,
EC_BLOCK_HEIGHT INT DEFAULT NULL SELECTIVITY 20,
EC_BLOCK_ID BIGINT DEFAULT NULL SELECTIVITY 20,
HAS_ENCRYPTTOSELF_MESSAGE BOOLEAN DEFAULT FALSE NOT NULL SELECTIVITY 1,
HAS_PRUNABLE_MESSAGE BOOLEAN DEFAULT FALSE NOT NULL SELECTIVITY 1,
HAS_PRUNABLE_ENCRYPTED_MESSAGE BOOLEAN DEFAULT FALSE NOT NULL SELECTIVITY 1,
HAS_PRUNABLE_ATTACHMENT BOOLEAN DEFAULT FALSE NOT NULL SELECTIVITY 1
);
ALTER TABLE PUBLIC.TRANSACTION ADD CONSTRAINT PUBLIC.transasaction_pk PRIMARY KEY(DB_ID);
-- 1425 +/- SELECT COUNT(*) FROM PUBLIC.TRANSACTION;
CREATE UNIQUE INDEX PUBLIC.TRANSACTION_ID_IDX ON PUBLIC.TRANSACTION(ID);
CREATE INDEX PUBLIC.TRANSACTION_SENDER_ID_IDX ON PUBLIC.TRANSACTION(SENDER_ID);
CREATE INDEX PUBLIC.TRANSACTION_RECIPIENT_ID_IDX ON PUBLIC.TRANSACTION(RECIPIENT_ID);
CREATE INDEX PUBLIC.TRANSACTION_BLOCK_TIMESTAMP_IDX ON PUBLIC.TRANSACTION(BLOCK_TIMESTAMP DESC);
CREATE CACHED TABLE PUBLIC.PEER(
ADDRESS VARCHAR NOT NULL SELECTIVITY 100,
LAST_UPDATED INT SELECTIVITY 37,
SERVICES BIGINT SELECTIVITY 12
);
ALTER TABLE PUBLIC.PEER ADD CONSTRAINT PUBLIC.CONSTRAINT_2 PRIMARY KEY(ADDRESS);
-- 8 +/- SELECT COUNT(*) FROM PUBLIC.PEER;
CREATE CACHED TABLE PUBLIC.ALIAS(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_718413A2_E908_474F_A271_CE6FA8B902BA) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_718413A2_E908_474F_A271_CE6FA8B902BA SELECTIVITY 100,
ID BIGINT NOT NULL SELECTIVITY 100,
ACCOUNT_ID BIGINT NOT NULL SELECTIVITY 6,
ALIAS_NAME VARCHAR NOT NULL SELECTIVITY 100,
ALIAS_NAME_LOWER VARCHAR AS LOWER(ALIAS_NAME) NOT NULL SELECTIVITY 100,
ALIAS_URI VARCHAR NOT NULL SELECTIVITY 13,
TIMESTAMP INT NOT NULL SELECTIVITY 100,
HEIGHT INT NOT NULL SELECTIVITY 100,
LATEST BOOLEAN DEFAULT TRUE NOT NULL SELECTIVITY 3
);
ALTER TABLE PUBLIC.ALIAS ADD CONSTRAINT PUBLIC.CONSTRAINT_3B PRIMARY KEY(DB_ID);
-- 29 +/- SELECT COUNT(*) FROM PUBLIC.ALIAS;
CREATE UNIQUE INDEX PUBLIC.ALIAS_ID_HEIGHT_IDX ON PUBLIC.ALIAS(ID, HEIGHT DESC);
CREATE INDEX PUBLIC.ALIAS_ACCOUNT_ID_IDX ON PUBLIC.ALIAS(ACCOUNT_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.ALIAS_NAME_LOWER_IDX ON PUBLIC.ALIAS(ALIAS_NAME_LOWER);
CREATE INDEX PUBLIC.ALIAS_HEIGHT_ID_IDX ON PUBLIC.ALIAS(HEIGHT, ID);
CREATE CACHED TABLE PUBLIC.ALIAS_OFFER(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_EDD8D597_4F39_4017_9389_FA7A5C612999) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_EDD8D597_4F39_4017_9389_FA7A5C612999,
ID BIGINT NOT NULL,
PRICE BIGINT NOT NULL,
BUYER_ID BIGINT,
HEIGHT INT NOT NULL,
LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
ALTER TABLE PUBLIC.ALIAS_OFFER ADD CONSTRAINT PUBLIC.CONSTRAINT_C PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ALIAS_OFFER;
CREATE UNIQUE INDEX PUBLIC.ALIAS_OFFER_ID_HEIGHT_IDX ON PUBLIC.ALIAS_OFFER(ID, HEIGHT DESC);
CREATE INDEX PUBLIC.ALIAS_OFFER_HEIGHT_ID_IDX ON PUBLIC.ALIAS_OFFER(HEIGHT, ID);
CREATE CACHED TABLE PUBLIC.ASSET(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_AA49D29A_2B05_4B3E_BAF7_EF691491A36E) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_AA49D29A_2B05_4B3E_BAF7_EF691491A36E SELECTIVITY 100,
ID BIGINT NOT NULL SELECTIVITY 100,
ACCOUNT_ID BIGINT NOT NULL SELECTIVITY 100,
NAME VARCHAR NOT NULL SELECTIVITY 100,
DESCRIPTION VARCHAR SELECTIVITY 100,
QUANTITY BIGINT NOT NULL SELECTIVITY 50,
DECIMALS TINYINT NOT NULL SELECTIVITY 50,
INITIAL_QUANTITY BIGINT NOT NULL SELECTIVITY 50,
HEIGHT INT NOT NULL SELECTIVITY 100,
LATEST BOOLEAN DEFAULT TRUE NOT NULL SELECTIVITY 50
);
ALTER TABLE PUBLIC.ASSET ADD CONSTRAINT PUBLIC.CONSTRAINT_3BA PRIMARY KEY(DB_ID);
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.ASSET;
CREATE INDEX PUBLIC.ASSET_ACCOUNT_ID_IDX ON PUBLIC.ASSET(ACCOUNT_ID);
CREATE UNIQUE INDEX PUBLIC.ASSET_ID_HEIGHT_IDX ON PUBLIC.ASSET(ID, HEIGHT DESC);
CREATE INDEX PUBLIC.ASSET_HEIGHT_ID_IDX ON PUBLIC.ASSET(HEIGHT, ID);
CREATE CACHED TABLE PUBLIC.TRADE(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_4B14966A_B157_49F1_ADC6_4F20F363B47B) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_4B14966A_B157_49F1_ADC6_4F20F363B47B,
ASSET_ID BIGINT NOT NULL,
BLOCK_ID BIGINT NOT NULL,
ASK_ORDER_ID BIGINT NOT NULL,
BID_ORDER_ID BIGINT NOT NULL,
ASK_ORDER_HEIGHT INT NOT NULL,
BID_ORDER_HEIGHT INT NOT NULL,
SELLER_ID BIGINT NOT NULL,
BUYER_ID BIGINT NOT NULL,
IS_BUY BOOLEAN NOT NULL,
QUANTITY BIGINT NOT NULL,
PRICE BIGINT NOT NULL,
TIMESTAMP INT NOT NULL,
HEIGHT INT NOT NULL
);
ALTER TABLE PUBLIC.TRADE ADD CONSTRAINT PUBLIC.CONSTRAINT_4 PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TRADE;
CREATE INDEX PUBLIC.TRADE_ASSET_ID_IDX ON PUBLIC.TRADE(ASSET_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.TRADE_SELLER_ID_IDX ON PUBLIC.TRADE(SELLER_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.TRADE_BUYER_ID_IDX ON PUBLIC.TRADE(BUYER_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.TRADE_HEIGHT_IDX ON PUBLIC.TRADE(HEIGHT);
CREATE INDEX PUBLIC.TRADE_ASK_IDX ON PUBLIC.TRADE(ASK_ORDER_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.TRADE_BID_IDX ON PUBLIC.TRADE(BID_ORDER_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.TRADE_HEIGHT_DB_ID_IDX ON PUBLIC.TRADE(HEIGHT DESC, DB_ID DESC);
CREATE CACHED TABLE PUBLIC.ASK_ORDER(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_0E41089D_E736_4111_AF26_E421C68C9257) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_0E41089D_E736_4111_AF26_E421C68C9257 SELECTIVITY 100,
ID BIGINT NOT NULL SELECTIVITY 100,
ACCOUNT_ID BIGINT NOT NULL SELECTIVITY 100,
ASSET_ID BIGINT NOT NULL SELECTIVITY 100,
PRICE BIGINT NOT NULL SELECTIVITY 100,
TRANSACTION_INDEX SMALLINT NOT NULL SELECTIVITY 100,
TRANSACTION_HEIGHT INT NOT NULL SELECTIVITY 100,
QUANTITY BIGINT NOT NULL SELECTIVITY 100,
CREATION_HEIGHT INT NOT NULL SELECTIVITY 100,
HEIGHT INT NOT NULL SELECTIVITY 100,
LATEST BOOLEAN DEFAULT TRUE NOT NULL SELECTIVITY 100
);
ALTER TABLE PUBLIC.ASK_ORDER ADD CONSTRAINT PUBLIC.CONSTRAINT_7 PRIMARY KEY(DB_ID);
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.ASK_ORDER;
CREATE UNIQUE INDEX PUBLIC.ASK_ORDER_ID_HEIGHT_IDX ON PUBLIC.ASK_ORDER(ID, HEIGHT DESC);
CREATE INDEX PUBLIC.ASK_ORDER_ACCOUNT_ID_IDX ON PUBLIC.ASK_ORDER(ACCOUNT_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.ASK_ORDER_ASSET_ID_PRICE_IDX ON PUBLIC.ASK_ORDER(ASSET_ID, PRICE);
CREATE INDEX PUBLIC.ASK_ORDER_CREATION_IDX ON PUBLIC.ASK_ORDER(CREATION_HEIGHT DESC);
CREATE INDEX PUBLIC.ASK_ORDER_HEIGHT_ID_IDX ON PUBLIC.ASK_ORDER(HEIGHT, ID);
CREATE CACHED TABLE PUBLIC.BID_ORDER(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_B5CE36E2_88F6_4AEA_9BEE_51A9844B8921) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_B5CE36E2_88F6_4AEA_9BEE_51A9844B8921,
ID BIGINT NOT NULL,
ACCOUNT_ID BIGINT NOT NULL,
ASSET_ID BIGINT NOT NULL,
PRICE BIGINT NOT NULL,
TRANSACTION_INDEX SMALLINT NOT NULL,
TRANSACTION_HEIGHT INT NOT NULL,
QUANTITY BIGINT NOT NULL,
CREATION_HEIGHT INT NOT NULL,
HEIGHT INT NOT NULL,
LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
ALTER TABLE PUBLIC.BID_ORDER ADD CONSTRAINT PUBLIC.CONSTRAINT_8 PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.BID_ORDER;
CREATE UNIQUE INDEX PUBLIC.BID_ORDER_ID_HEIGHT_IDX ON PUBLIC.BID_ORDER(ID, HEIGHT DESC);
CREATE INDEX PUBLIC.BID_ORDER_ACCOUNT_ID_IDX ON PUBLIC.BID_ORDER(ACCOUNT_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.BID_ORDER_ASSET_ID_PRICE_IDX ON PUBLIC.BID_ORDER(ASSET_ID, PRICE DESC);
CREATE INDEX PUBLIC.BID_ORDER_CREATION_IDX ON PUBLIC.BID_ORDER(CREATION_HEIGHT DESC);
CREATE INDEX PUBLIC.BID_ORDER_HEIGHT_ID_IDX ON PUBLIC.BID_ORDER(HEIGHT, ID);
CREATE CACHED TABLE PUBLIC.GOODS(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_D79BD2C8_34A5_43A9_AE4C_593CA197BCC4) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_D79BD2C8_34A5_43A9_AE4C_593CA197BCC4,
ID BIGINT NOT NULL,
SELLER_ID BIGINT NOT NULL,
NAME VARCHAR NOT NULL,
DESCRIPTION VARCHAR,
PARSED_TAGS ARRAY,
HAS_IMAGE BOOLEAN NOT NULL,
TAGS VARCHAR,
TIMESTAMP INT NOT NULL,
QUANTITY INT NOT NULL,
PRICE BIGINT NOT NULL,
DELISTED BOOLEAN NOT NULL,
HEIGHT INT NOT NULL,
LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
ALTER TABLE PUBLIC.GOODS ADD CONSTRAINT PUBLIC.CONSTRAINT_40 PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.GOODS;
CREATE UNIQUE INDEX PUBLIC.GOODS_ID_HEIGHT_IDX ON PUBLIC.GOODS(ID, HEIGHT DESC);
CREATE INDEX PUBLIC.GOODS_SELLER_ID_NAME_IDX ON PUBLIC.GOODS(SELLER_ID, NAME);
CREATE INDEX PUBLIC.GOODS_TIMESTAMP_IDX ON PUBLIC.GOODS(TIMESTAMP DESC, HEIGHT DESC);
CREATE INDEX PUBLIC.GOODS_HEIGHT_ID_IDX ON PUBLIC.GOODS(HEIGHT, ID);
CREATE CACHED TABLE PUBLIC.PURCHASE(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_02FB98B3_12CC_4144_85DF_974ED1D2DBC9) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_02FB98B3_12CC_4144_85DF_974ED1D2DBC9,
ID BIGINT NOT NULL,
BUYER_ID BIGINT NOT NULL,
GOODS_ID BIGINT NOT NULL,
SELLER_ID BIGINT NOT NULL,
QUANTITY INT NOT NULL,
PRICE BIGINT NOT NULL,
DEADLINE INT NOT NULL,
NOTE VARBINARY,
NONCE BINARY(32),
TIMESTAMP INT NOT NULL,
PENDING BOOLEAN NOT NULL,
GOODS VARBINARY,
GOODS_NONCE BINARY(32),
GOODS_IS_TEXT BOOLEAN DEFAULT TRUE NOT NULL,
REFUND_NOTE VARBINARY,
REFUND_NONCE BINARY(32),
HAS_FEEDBACK_NOTES BOOLEAN DEFAULT FALSE NOT NULL,
HAS_PUBLIC_FEEDBACKS BOOLEAN DEFAULT FALSE NOT NULL,
DISCOUNT BIGINT NOT NULL,
REFUND BIGINT NOT NULL,
HEIGHT INT NOT NULL,
LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
ALTER TABLE PUBLIC.PURCHASE ADD CONSTRAINT PUBLIC.CONSTRAINT_9 PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PURCHASE;
CREATE UNIQUE INDEX PUBLIC.PURCHASE_ID_HEIGHT_IDX ON PUBLIC.PURCHASE(ID, HEIGHT DESC);
CREATE INDEX PUBLIC.PURCHASE_BUYER_ID_HEIGHT_IDX ON PUBLIC.PURCHASE(BUYER_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.PURCHASE_SELLER_ID_HEIGHT_IDX ON PUBLIC.PURCHASE(SELLER_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.PURCHASE_DEADLINE_IDX ON PUBLIC.PURCHASE(DEADLINE DESC, HEIGHT DESC);
CREATE INDEX PUBLIC.PURCHASE_TIMESTAMP_IDX ON PUBLIC.PURCHASE(TIMESTAMP DESC, ID);
CREATE INDEX PUBLIC.PURCHASE_HEIGHT_ID_IDX ON PUBLIC.PURCHASE(HEIGHT, ID);
CREATE CACHED TABLE PUBLIC.ACCOUNT(
DB_ID BIGINT DEFAULT  PUBLIC.ACCOUNT_SEQ.nextval NOT NULL ,
ID BIGINT NOT NULL ,
BALANCE BIGINT NOT NULL,
UNCONFIRMED_BALANCE BIGINT NOT NULL,
HAS_CONTROL_PHASING BOOLEAN DEFAULT FALSE NOT NULL,
FORGED_BALANCE BIGINT NOT NULL,
ACTIVE_LESSEE_ID BIGINT,
HEIGHT INT NOT NULL ,
LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
ALTER TABLE PUBLIC.ACCOUNT ADD CONSTRAINT PUBLIC.CONSTRAINT_E PRIMARY KEY(DB_ID);
-- 85057 +/- SELECT COUNT(*) FROM PUBLIC.ACCOUNT;
CREATE UNIQUE INDEX PUBLIC.ACCOUNT_ID_HEIGHT_IDX ON PUBLIC.ACCOUNT(ID, HEIGHT DESC);
CREATE INDEX PUBLIC.ACCOUNT_ACTIVE_LESSEE_ID_IDX ON PUBLIC.ACCOUNT(ACTIVE_LESSEE_ID);
CREATE INDEX PUBLIC.ACCOUNT_HEIGHT_ID_IDX ON PUBLIC.ACCOUNT(HEIGHT, ID);
CREATE CACHED TABLE PUBLIC.ACCOUNT_ASSET(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_8F0B3C14_9D25_4D6A_A966_A76CF0A5CA31) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_8F0B3C14_9D25_4D6A_A966_A76CF0A5CA31 SELECTIVITY 100,
ACCOUNT_ID BIGINT NOT NULL SELECTIVITY 100,
ASSET_ID BIGINT NOT NULL SELECTIVITY 100,
QUANTITY BIGINT NOT NULL SELECTIVITY 50,
UNCONFIRMED_QUANTITY BIGINT NOT NULL SELECTIVITY 100,
HEIGHT INT NOT NULL SELECTIVITY 100,
LATEST BOOLEAN DEFAULT TRUE NOT NULL SELECTIVITY 50
);
ALTER TABLE PUBLIC.ACCOUNT_ASSET ADD CONSTRAINT PUBLIC.CONSTRAINT_CF PRIMARY KEY(DB_ID);
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.ACCOUNT_ASSET;
CREATE UNIQUE INDEX PUBLIC.ACCOUNT_ASSET_ID_HEIGHT_IDX ON PUBLIC.ACCOUNT_ASSET(ACCOUNT_ID, ASSET_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.ACCOUNT_ASSET_QUANTITY_IDX ON PUBLIC.ACCOUNT_ASSET(QUANTITY DESC);
CREATE INDEX PUBLIC.ACCOUNT_ASSET_ASSET_ID_IDX ON PUBLIC.ACCOUNT_ASSET(ASSET_ID);
CREATE INDEX PUBLIC.ACCOUNT_ASSET_HEIGHT_ID_IDX ON PUBLIC.ACCOUNT_ASSET(HEIGHT, ACCOUNT_ID, ASSET_ID);
CREATE CACHED TABLE PUBLIC.ACCOUNT_GUARANTEED_BALANCE(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_59B00FDF_11A3_4A7F_A37A_4308091108E4) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_59B00FDF_11A3_4A7F_A37A_4308091108E4,
ACCOUNT_ID BIGINT NOT NULL,
ADDITIONS BIGINT NOT NULL,
HEIGHT INT NOT NULL
);
ALTER TABLE PUBLIC.ACCOUNT_GUARANTEED_BALANCE ADD CONSTRAINT PUBLIC.CONSTRAINT_A PRIMARY KEY(DB_ID);
-- 178 +/- SELECT COUNT(*) FROM PUBLIC.ACCOUNT_GUARANTEED_BALANCE;
CREATE UNIQUE INDEX PUBLIC.ACCOUNT_GUARANTEED_BALANCE_ID_HEIGHT_IDX ON PUBLIC.ACCOUNT_GUARANTEED_BALANCE(ACCOUNT_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.ACCOUNT_GUARANTEED_BALANCE_HEIGHT_IDX ON PUBLIC.ACCOUNT_GUARANTEED_BALANCE(HEIGHT);
CREATE CACHED TABLE PUBLIC.PURCHASE_FEEDBACK(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_7F4860EF_5B61_48B9_850B_0CC5FFF4E6C3) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_7F4860EF_5B61_48B9_850B_0CC5FFF4E6C3,
ID BIGINT NOT NULL,
FEEDBACK_DATA VARBINARY NOT NULL,
FEEDBACK_NONCE BINARY(32) NOT NULL,
HEIGHT INT NOT NULL,
LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
ALTER TABLE PUBLIC.PURCHASE_FEEDBACK ADD CONSTRAINT PUBLIC.CONSTRAINT_4F PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PURCHASE_FEEDBACK;
CREATE INDEX PUBLIC.PURCHASE_FEEDBACK_ID_HEIGHT_IDX ON PUBLIC.PURCHASE_FEEDBACK(ID, HEIGHT DESC);
CREATE INDEX PUBLIC.PURCHASE_FEEDBACK_HEIGHT_ID_IDX ON PUBLIC.PURCHASE_FEEDBACK(HEIGHT, ID);
CREATE CACHED TABLE PUBLIC.PURCHASE_PUBLIC_FEEDBACK(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_84EDC395_10D8_4200_AF6E_B0986FAE40BC) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_84EDC395_10D8_4200_AF6E_B0986FAE40BC,
ID BIGINT NOT NULL,
PUBLIC_FEEDBACK VARCHAR NOT NULL,
HEIGHT INT NOT NULL,
LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
ALTER TABLE PUBLIC.PURCHASE_PUBLIC_FEEDBACK ADD CONSTRAINT PUBLIC.CONSTRAINT_B PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PURCHASE_PUBLIC_FEEDBACK;
CREATE INDEX PUBLIC.PURCHASE_PUBLIC_FEEDBACK_ID_HEIGHT_IDX ON PUBLIC.PURCHASE_PUBLIC_FEEDBACK(ID, HEIGHT DESC);
CREATE INDEX PUBLIC.PURCHASE_PUBLIC_FEEDBACK_HEIGHT_ID_IDX ON PUBLIC.PURCHASE_PUBLIC_FEEDBACK(HEIGHT, ID);
CREATE CACHED TABLE PUBLIC.UNCONFIRMED_TRANSACTION(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_E0D63F78_469E_498A_B38D_CDF174A6EBE8) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_E0D63F78_469E_498A_B38D_CDF174A6EBE8,
ID BIGINT NOT NULL,
EXPIRATION INT NOT NULL,
TRANSACTION_HEIGHT INT NOT NULL,
FEE_PER_BYTE BIGINT NOT NULL,
ARRIVAL_TIMESTAMP BIGINT NOT NULL,
TRANSACTION_BYTES VARBINARY NOT NULL,
PRUNABLE_JSON VARCHAR,
HEIGHT INT NOT NULL
);
ALTER TABLE PUBLIC.UNCONFIRMED_TRANSACTION ADD CONSTRAINT PUBLIC.CONSTRAINT_2E PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.UNCONFIRMED_TRANSACTION;
CREATE UNIQUE INDEX PUBLIC.UNCONFIRMED_TRANSACTION_ID_IDX ON PUBLIC.UNCONFIRMED_TRANSACTION(ID);
CREATE INDEX PUBLIC.UNCONFIRMED_TRANSACTION_HEIGHT_FEE_TIMESTAMP_IDX ON PUBLIC.UNCONFIRMED_TRANSACTION(TRANSACTION_HEIGHT, FEE_PER_BYTE DESC, ARRIVAL_TIMESTAMP);
CREATE INDEX PUBLIC.UNCONFIRMED_TRANSACTION_EXPIRATION_IDX ON PUBLIC.UNCONFIRMED_TRANSACTION(EXPIRATION DESC);
CREATE CACHED TABLE PUBLIC.ASSET_TRANSFER(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_043ABA9A_85EA_4BF4_9625_10C45E7923FD) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_043ABA9A_85EA_4BF4_9625_10C45E7923FD,
ID BIGINT NOT NULL,
ASSET_ID BIGINT NOT NULL,
SENDER_ID BIGINT NOT NULL,
RECIPIENT_ID BIGINT NOT NULL,
QUANTITY BIGINT NOT NULL,
TIMESTAMP INT NOT NULL,
HEIGHT INT NOT NULL
);
ALTER TABLE PUBLIC.ASSET_TRANSFER ADD CONSTRAINT PUBLIC.CONSTRAINT_F6 PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ASSET_TRANSFER;
CREATE UNIQUE INDEX PUBLIC.ASSET_TRANSFER_ID_IDX ON PUBLIC.ASSET_TRANSFER(ID);
CREATE INDEX PUBLIC.ASSET_TRANSFER_ASSET_ID_IDX ON PUBLIC.ASSET_TRANSFER(ASSET_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.ASSET_TRANSFER_SENDER_ID_IDX ON PUBLIC.ASSET_TRANSFER(SENDER_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.ASSET_TRANSFER_RECIPIENT_ID_IDX ON PUBLIC.ASSET_TRANSFER(RECIPIENT_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.ASSET_TRANSFER_HEIGHT_IDX ON PUBLIC.ASSET_TRANSFER(HEIGHT);
CREATE CACHED TABLE PUBLIC.TAG(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_91787B50_FAC6_40E0_AE37_29DAA7913218) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_91787B50_FAC6_40E0_AE37_29DAA7913218,
TAG VARCHAR NOT NULL,
IN_STOCK_COUNT INT NOT NULL,
TOTAL_COUNT INT NOT NULL,
HEIGHT INT NOT NULL,
LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
ALTER TABLE PUBLIC.TAG ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TAG;
CREATE UNIQUE INDEX PUBLIC.TAG_TAG_IDX ON PUBLIC.TAG(TAG, HEIGHT DESC);
CREATE INDEX PUBLIC.TAG_IN_STOCK_COUNT_IDX ON PUBLIC.TAG(IN_STOCK_COUNT DESC, HEIGHT DESC);
CREATE INDEX PUBLIC.TAG_HEIGHT_TAG_IDX ON PUBLIC.TAG(HEIGHT, TAG);
CREATE CACHED TABLE PUBLIC.CURRENCY(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_48C49157_56EB_4C58_8760_3A7F0AB8C474) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_48C49157_56EB_4C58_8760_3A7F0AB8C474,
ID BIGINT NOT NULL,
ACCOUNT_ID BIGINT NOT NULL,
NAME VARCHAR NOT NULL,
NAME_LOWER VARCHAR AS LOWER(NAME) NOT NULL,
CODE VARCHAR NOT NULL,
DESCRIPTION VARCHAR,
TYPE INT NOT NULL,
INITIAL_SUPPLY BIGINT DEFAULT 0 NOT NULL,
RESERVE_SUPPLY BIGINT NOT NULL,
MAX_SUPPLY BIGINT NOT NULL,
CREATION_HEIGHT INT NOT NULL,
ISSUANCE_HEIGHT INT NOT NULL,
MIN_RESERVE_PER_UNIT_NQT BIGINT NOT NULL,
MIN_DIFFICULTY TINYINT NOT NULL,
MAX_DIFFICULTY TINYINT NOT NULL,
RULESET TINYINT NOT NULL,
ALGORITHM TINYINT NOT NULL,
DECIMALS TINYINT DEFAULT 0 NOT NULL,
HEIGHT INT NOT NULL,
LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
ALTER TABLE PUBLIC.CURRENCY ADD CONSTRAINT PUBLIC.CONSTRAINT_5 PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CURRENCY;
CREATE UNIQUE INDEX PUBLIC.CURRENCY_ID_HEIGHT_IDX ON PUBLIC.CURRENCY(ID, HEIGHT DESC);
CREATE INDEX PUBLIC.CURRENCY_ACCOUNT_ID_IDX ON PUBLIC.CURRENCY(ACCOUNT_ID);
CREATE INDEX PUBLIC.CURRENCY_NAME_IDX ON PUBLIC.CURRENCY(NAME_LOWER, HEIGHT DESC);
CREATE INDEX PUBLIC.CURRENCY_CODE_IDX ON PUBLIC.CURRENCY(CODE, HEIGHT DESC);
CREATE INDEX PUBLIC.CURRENCY_CREATION_HEIGHT_IDX ON PUBLIC.CURRENCY(CREATION_HEIGHT DESC);
CREATE INDEX PUBLIC.CURRENCY_ISSUANCE_HEIGHT_IDX ON PUBLIC.CURRENCY(ISSUANCE_HEIGHT);
CREATE INDEX PUBLIC.CURRENCY_HEIGHT_ID_IDX ON PUBLIC.CURRENCY(HEIGHT, ID);
CREATE CACHED TABLE PUBLIC.ACCOUNT_CURRENCY(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_54D3687D_B190_410C_AF6C_0A568995B8C6) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_54D3687D_B190_410C_AF6C_0A568995B8C6,
ACCOUNT_ID BIGINT NOT NULL,
CURRENCY_ID BIGINT NOT NULL,
UNITS BIGINT NOT NULL,
UNCONFIRMED_UNITS BIGINT NOT NULL,
HEIGHT INT NOT NULL,
LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
ALTER TABLE PUBLIC.ACCOUNT_CURRENCY ADD CONSTRAINT PUBLIC.CONSTRAINT_EC PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ACCOUNT_CURRENCY;
CREATE UNIQUE INDEX PUBLIC.ACCOUNT_CURRENCY_ID_HEIGHT_IDX ON PUBLIC.ACCOUNT_CURRENCY(ACCOUNT_ID, CURRENCY_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.ACCOUNT_CURRENCY_UNITS_IDX ON PUBLIC.ACCOUNT_CURRENCY(UNITS DESC);
CREATE INDEX PUBLIC.ACCOUNT_CURRENCY_CURRENCY_ID_IDX ON PUBLIC.ACCOUNT_CURRENCY(CURRENCY_ID);
CREATE INDEX PUBLIC.ACCOUNT_CURRENCY_HEIGHT_ID_IDX ON PUBLIC.ACCOUNT_CURRENCY(HEIGHT, ACCOUNT_ID, CURRENCY_ID);
CREATE CACHED TABLE PUBLIC.CURRENCY_FOUNDER(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_D4541341_31D1_4A31_9D63_A61D37917069) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_D4541341_31D1_4A31_9D63_A61D37917069,
CURRENCY_ID BIGINT NOT NULL,
ACCOUNT_ID BIGINT NOT NULL,
AMOUNT BIGINT NOT NULL,
HEIGHT INT NOT NULL,
LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
ALTER TABLE PUBLIC.CURRENCY_FOUNDER ADD CONSTRAINT PUBLIC.CONSTRAINT_18 PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CURRENCY_FOUNDER;
CREATE UNIQUE INDEX PUBLIC.CURRENCY_FOUNDER_CURRENCY_ID_IDX ON PUBLIC.CURRENCY_FOUNDER(CURRENCY_ID, ACCOUNT_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.CURRENCY_FOUNDER_ACCOUNT_ID_IDX ON PUBLIC.CURRENCY_FOUNDER(ACCOUNT_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.CURRENCY_FOUNDER_HEIGHT_ID_IDX ON PUBLIC.CURRENCY_FOUNDER(HEIGHT, CURRENCY_ID, ACCOUNT_ID);
CREATE CACHED TABLE PUBLIC.CURRENCY_MINT(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_6AC14DF9_84FB_4296_A7EB_6F1F2A0F5730) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_6AC14DF9_84FB_4296_A7EB_6F1F2A0F5730,
CURRENCY_ID BIGINT NOT NULL,
ACCOUNT_ID BIGINT NOT NULL,
COUNTER BIGINT NOT NULL,
HEIGHT INT NOT NULL,
LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
ALTER TABLE PUBLIC.CURRENCY_MINT ADD CONSTRAINT PUBLIC.CONSTRAINT_FD PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CURRENCY_MINT;
CREATE UNIQUE INDEX PUBLIC.CURRENCY_MINT_CURRENCY_ID_ACCOUNT_ID_IDX ON PUBLIC.CURRENCY_MINT(CURRENCY_ID, ACCOUNT_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.CURRENCY_MINT_HEIGHT_ID_IDX ON PUBLIC.CURRENCY_MINT(HEIGHT, CURRENCY_ID, ACCOUNT_ID);
CREATE CACHED TABLE PUBLIC.BUY_OFFER(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_E2FCA41B_6117_4C7E_9EF5_335C2F4A3F0A) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_E2FCA41B_6117_4C7E_9EF5_335C2F4A3F0A,
ID BIGINT NOT NULL,
CURRENCY_ID BIGINT NOT NULL,
ACCOUNT_ID BIGINT NOT NULL,
RATE BIGINT NOT NULL,
UNIT_LIMIT BIGINT NOT NULL,
SUPPLY BIGINT NOT NULL,
EXPIRATION_HEIGHT INT NOT NULL,
CREATION_HEIGHT INT NOT NULL,
TRANSACTION_INDEX SMALLINT NOT NULL,
TRANSACTION_HEIGHT INT NOT NULL,
HEIGHT INT NOT NULL,
LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
ALTER TABLE PUBLIC.BUY_OFFER ADD CONSTRAINT PUBLIC.CONSTRAINT_C2 PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.BUY_OFFER;
CREATE UNIQUE INDEX PUBLIC.BUY_OFFER_ID_IDX ON PUBLIC.BUY_OFFER(ID, HEIGHT DESC);
CREATE INDEX PUBLIC.BUY_OFFER_CURRENCY_ID_ACCOUNT_ID_IDX ON PUBLIC.BUY_OFFER(CURRENCY_ID, ACCOUNT_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.BUY_OFFER_RATE_HEIGHT_IDX ON PUBLIC.BUY_OFFER(RATE DESC, CREATION_HEIGHT);
CREATE INDEX PUBLIC.BUY_OFFER_HEIGHT_ID_IDX ON PUBLIC.BUY_OFFER(HEIGHT, ID);
CREATE CACHED TABLE PUBLIC.SELL_OFFER(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_FA292EF3_DA05_400A_9853_E6D54ECC908E) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_FA292EF3_DA05_400A_9853_E6D54ECC908E,
ID BIGINT NOT NULL,
CURRENCY_ID BIGINT NOT NULL,
ACCOUNT_ID BIGINT NOT NULL,
RATE BIGINT NOT NULL,
UNIT_LIMIT BIGINT NOT NULL,
SUPPLY BIGINT NOT NULL,
EXPIRATION_HEIGHT INT NOT NULL,
CREATION_HEIGHT INT NOT NULL,
TRANSACTION_INDEX SMALLINT NOT NULL,
TRANSACTION_HEIGHT INT NOT NULL,
HEIGHT INT NOT NULL,
LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
ALTER TABLE PUBLIC.SELL_OFFER ADD CONSTRAINT PUBLIC.CONSTRAINT_5C PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SELL_OFFER;
CREATE UNIQUE INDEX PUBLIC.SELL_OFFER_ID_IDX ON PUBLIC.SELL_OFFER(ID, HEIGHT DESC);
CREATE INDEX PUBLIC.SELL_OFFER_CURRENCY_ID_ACCOUNT_ID_IDX ON PUBLIC.SELL_OFFER(CURRENCY_ID, ACCOUNT_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.SELL_OFFER_RATE_HEIGHT_IDX ON PUBLIC.SELL_OFFER(RATE, CREATION_HEIGHT);
CREATE INDEX PUBLIC.SELL_OFFER_HEIGHT_ID_IDX ON PUBLIC.SELL_OFFER(HEIGHT, ID);
CREATE CACHED TABLE PUBLIC.EXCHANGE(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_52579908_9D92_4A43_9A02_A8E092DC81E7) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_52579908_9D92_4A43_9A02_A8E092DC81E7,
TRANSACTION_ID BIGINT NOT NULL,
CURRENCY_ID BIGINT NOT NULL,
BLOCK_ID BIGINT NOT NULL,
OFFER_ID BIGINT NOT NULL,
SELLER_ID BIGINT NOT NULL,
BUYER_ID BIGINT NOT NULL,
UNITS BIGINT NOT NULL,
RATE BIGINT NOT NULL,
TIMESTAMP INT NOT NULL,
HEIGHT INT NOT NULL
);
ALTER TABLE PUBLIC.EXCHANGE ADD CONSTRAINT PUBLIC.CONSTRAINT_A5 PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.EXCHANGE;
CREATE UNIQUE INDEX PUBLIC.EXCHANGE_OFFER_IDX ON PUBLIC.EXCHANGE(TRANSACTION_ID, OFFER_ID);
CREATE INDEX PUBLIC.EXCHANGE_CURRENCY_ID_IDX ON PUBLIC.EXCHANGE(CURRENCY_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.EXCHANGE_SELLER_ID_IDX ON PUBLIC.EXCHANGE(SELLER_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.EXCHANGE_BUYER_ID_IDX ON PUBLIC.EXCHANGE(BUYER_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.EXCHANGE_HEIGHT_IDX ON PUBLIC.EXCHANGE(HEIGHT);
CREATE INDEX PUBLIC.EXCHANGE_HEIGHT_DB_ID_IDX ON PUBLIC.EXCHANGE(HEIGHT DESC, DB_ID DESC);
CREATE CACHED TABLE PUBLIC.CURRENCY_TRANSFER(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_EE17D780_F458_4947_A843_B159E2E62EB3) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_EE17D780_F458_4947_A843_B159E2E62EB3,
ID BIGINT NOT NULL,
CURRENCY_ID BIGINT NOT NULL,
SENDER_ID BIGINT NOT NULL,
RECIPIENT_ID BIGINT NOT NULL,
UNITS BIGINT NOT NULL,
TIMESTAMP INT NOT NULL,
HEIGHT INT NOT NULL
);
ALTER TABLE PUBLIC.CURRENCY_TRANSFER ADD CONSTRAINT PUBLIC.CONSTRAINT_2A PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CURRENCY_TRANSFER;
CREATE UNIQUE INDEX PUBLIC.CURRENCY_TRANSFER_ID_IDX ON PUBLIC.CURRENCY_TRANSFER(ID);
CREATE INDEX PUBLIC.CURRENCY_TRANSFER_CURRENCY_ID_IDX ON PUBLIC.CURRENCY_TRANSFER(CURRENCY_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.CURRENCY_TRANSFER_SENDER_ID_IDX ON PUBLIC.CURRENCY_TRANSFER(SENDER_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.CURRENCY_TRANSFER_RECIPIENT_ID_IDX ON PUBLIC.CURRENCY_TRANSFER(RECIPIENT_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.CURRENCY_TRANSFER_HEIGHT_IDX ON PUBLIC.CURRENCY_TRANSFER(HEIGHT);
CREATE CACHED TABLE PUBLIC.SCAN(
RESCAN BOOLEAN DEFAULT FALSE NOT NULL SELECTIVITY 100,
HEIGHT INT DEFAULT 0 NOT NULL SELECTIVITY 100,
VALIDATE BOOLEAN DEFAULT FALSE NOT NULL SELECTIVITY 100
);
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.SCAN;
CREATE CACHED TABLE PUBLIC.CURRENCY_SUPPLY(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_F4ED3006_C280_4E5C_8FC5_82D0A197B626) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_F4ED3006_C280_4E5C_8FC5_82D0A197B626,
ID BIGINT NOT NULL,
CURRENT_SUPPLY BIGINT NOT NULL,
CURRENT_RESERVE_PER_UNIT_NQT BIGINT NOT NULL,
HEIGHT INT NOT NULL,
LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
ALTER TABLE PUBLIC.CURRENCY_SUPPLY ADD CONSTRAINT PUBLIC.CONSTRAINT_F0 PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CURRENCY_SUPPLY;
CREATE UNIQUE INDEX PUBLIC.CURRENCY_SUPPLY_ID_HEIGHT_IDX ON PUBLIC.CURRENCY_SUPPLY(ID, HEIGHT DESC);
CREATE INDEX PUBLIC.CURRENCY_SUPPLY_HEIGHT_ID_IDX ON PUBLIC.CURRENCY_SUPPLY(HEIGHT, ID);
CREATE CACHED TABLE PUBLIC.PUBLIC_KEY(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_685BB3A9_D6B2_48C7_BDB5_A742310CF13E) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_685BB3A9_D6B2_48C7_BDB5_A742310CF13E SELECTIVITY 100,
ACCOUNT_ID BIGINT NOT NULL SELECTIVITY 100,
PUBLIC_KEY BINARY(32) SELECTIVITY 100,
HEIGHT INT NOT NULL SELECTIVITY 1,
LATEST BOOLEAN DEFAULT TRUE NOT NULL SELECTIVITY 1
);
ALTER TABLE PUBLIC.PUBLIC_KEY ADD CONSTRAINT PUBLIC.CONSTRAINT_8E PRIMARY KEY(DB_ID);
-- 258303 +/- SELECT COUNT(*) FROM PUBLIC.PUBLIC_KEY;
CREATE UNIQUE INDEX PUBLIC.PUBLIC_KEY_ACCOUNT_ID_HEIGHT_IDX ON PUBLIC.PUBLIC_KEY(ACCOUNT_ID, HEIGHT DESC);
CREATE CACHED TABLE PUBLIC.VOTE(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_87379CE4_8CD6_4EB3_AEBB_F1C23337272D) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_87379CE4_8CD6_4EB3_AEBB_F1C23337272D,
ID BIGINT NOT NULL,
POLL_ID BIGINT NOT NULL,
VOTER_ID BIGINT NOT NULL,
VOTE_BYTES VARBINARY NOT NULL,
HEIGHT INT NOT NULL
);
ALTER TABLE PUBLIC.VOTE ADD CONSTRAINT PUBLIC.CONSTRAINT_28 PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.VOTE;
CREATE UNIQUE INDEX PUBLIC.VOTE_ID_IDX ON PUBLIC.VOTE(ID);
CREATE UNIQUE INDEX PUBLIC.VOTE_POLL_ID_IDX ON PUBLIC.VOTE(POLL_ID, VOTER_ID);
CREATE INDEX PUBLIC.VOTE_HEIGHT_IDX ON PUBLIC.VOTE(HEIGHT);
CREATE CACHED TABLE PUBLIC.POLL(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_E2FAB68A_8FA4_4B34_8A9D_49393328ACF9) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_E2FAB68A_8FA4_4B34_8A9D_49393328ACF9,
ID BIGINT NOT NULL,
ACCOUNT_ID BIGINT NOT NULL,
NAME VARCHAR NOT NULL,
DESCRIPTION VARCHAR,
OPTIONS ARRAY NOT NULL,
MIN_NUM_OPTIONS TINYINT,
MAX_NUM_OPTIONS TINYINT,
MIN_RANGE_VALUE TINYINT,
MAX_RANGE_VALUE TINYINT,
TIMESTAMP INT NOT NULL,
FINISH_HEIGHT INT NOT NULL,
VOTING_MODEL TINYINT NOT NULL,
MIN_BALANCE BIGINT,
MIN_BALANCE_MODEL TINYINT,
HOLDING_ID BIGINT,
HEIGHT INT NOT NULL
);
ALTER TABLE PUBLIC.POLL ADD CONSTRAINT PUBLIC.CONSTRAINT_25 PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.POLL;
CREATE UNIQUE INDEX PUBLIC.POLL_ID_IDX ON PUBLIC.POLL(ID);
CREATE INDEX PUBLIC.POLL_HEIGHT_IDX ON PUBLIC.POLL(HEIGHT);
CREATE INDEX PUBLIC.POLL_ACCOUNT_IDX ON PUBLIC.POLL(ACCOUNT_ID);
CREATE INDEX PUBLIC.POLL_FINISH_HEIGHT_IDX ON PUBLIC.POLL(FINISH_HEIGHT DESC);
CREATE CACHED TABLE PUBLIC.POLL_RESULT(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_704D5836_6E55_4915_87A1_83489B758FFA) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_704D5836_6E55_4915_87A1_83489B758FFA,
POLL_ID BIGINT NOT NULL,
RESULT BIGINT,
WEIGHT BIGINT NOT NULL,
HEIGHT INT NOT NULL
);
ALTER TABLE PUBLIC.POLL_RESULT ADD CONSTRAINT PUBLIC.CONSTRAINT_F69 PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.POLL_RESULT;
CREATE INDEX PUBLIC.POLL_RESULT_POLL_ID_IDX ON PUBLIC.POLL_RESULT(POLL_ID);
CREATE INDEX PUBLIC.POLL_RESULT_HEIGHT_IDX ON PUBLIC.POLL_RESULT(HEIGHT);
CREATE CACHED TABLE PUBLIC.PHASING_POLL(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_D35883BE_EEDB_4D28_8C21_FEF7B5843D22) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_D35883BE_EEDB_4D28_8C21_FEF7B5843D22,
ID BIGINT NOT NULL,
ACCOUNT_ID BIGINT NOT NULL,
WHITELIST_SIZE TINYINT DEFAULT 0 NOT NULL,
FINISH_HEIGHT INT NOT NULL,
VOTING_MODEL TINYINT NOT NULL,
QUORUM BIGINT,
MIN_BALANCE BIGINT,
HOLDING_ID BIGINT,
MIN_BALANCE_MODEL TINYINT,
HASHED_SECRET VARBINARY,
ALGORITHM TINYINT,
HEIGHT INT NOT NULL
);
ALTER TABLE PUBLIC.PHASING_POLL ADD CONSTRAINT PUBLIC.CONSTRAINT_9C PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PHASING_POLL;
CREATE UNIQUE INDEX PUBLIC.PHASING_POLL_ID_IDX ON PUBLIC.PHASING_POLL(ID);
CREATE INDEX PUBLIC.PHASING_POLL_HEIGHT_IDX ON PUBLIC.PHASING_POLL(HEIGHT);
CREATE INDEX PUBLIC.PHASING_POLL_ACCOUNT_ID_IDX ON PUBLIC.PHASING_POLL(ACCOUNT_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.PHASING_POLL_HOLDING_ID_IDX ON PUBLIC.PHASING_POLL(HOLDING_ID, HEIGHT DESC);
CREATE CACHED TABLE PUBLIC.PHASING_VOTE(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_6FEACD8B_A449_4E4E_A341_8A33D0223BA7) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_6FEACD8B_A449_4E4E_A341_8A33D0223BA7,
VOTE_ID BIGINT NOT NULL,
TRANSACTION_ID BIGINT NOT NULL,
VOTER_ID BIGINT NOT NULL,
HEIGHT INT NOT NULL
);
ALTER TABLE PUBLIC.PHASING_VOTE ADD CONSTRAINT PUBLIC.CONSTRAINT_9C9 PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PHASING_VOTE;
CREATE UNIQUE INDEX PUBLIC.PHASING_VOTE_TRANSACTION_VOTER_IDX ON PUBLIC.PHASING_VOTE(TRANSACTION_ID, VOTER_ID);
CREATE INDEX PUBLIC.PHASING_VOTE_HEIGHT_IDX ON PUBLIC.PHASING_VOTE(HEIGHT);
CREATE CACHED TABLE PUBLIC.PHASING_POLL_VOTER(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_0C38A777_74DE_450C_BF80_7679A8B1EB9C) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_0C38A777_74DE_450C_BF80_7679A8B1EB9C,
TRANSACTION_ID BIGINT NOT NULL,
VOTER_ID BIGINT NOT NULL,
HEIGHT INT NOT NULL
);
ALTER TABLE PUBLIC.PHASING_POLL_VOTER ADD CONSTRAINT PUBLIC.CONSTRAINT_47 PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PHASING_POLL_VOTER;
CREATE UNIQUE INDEX PUBLIC.PHASING_POLL_VOTER_TRANSACTION_VOTER_IDX ON PUBLIC.PHASING_POLL_VOTER(TRANSACTION_ID, VOTER_ID);
CREATE INDEX PUBLIC.PHASING_POLL_VOTER_HEIGHT_IDX ON PUBLIC.PHASING_POLL_VOTER(HEIGHT);
CREATE CACHED TABLE PUBLIC.PHASING_POLL_RESULT(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_9B7D3FF0_A608_4A62_A8A0_F43FDBB4565C) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_9B7D3FF0_A608_4A62_A8A0_F43FDBB4565C SELECTIVITY 100,
ID BIGINT NOT NULL SELECTIVITY 100,
RESULT BIGINT NOT NULL SELECTIVITY 100,
APPROVED BOOLEAN NOT NULL SELECTIVITY 100,
HEIGHT INT NOT NULL SELECTIVITY 100
);
ALTER TABLE PUBLIC.PHASING_POLL_RESULT ADD CONSTRAINT PUBLIC.CONSTRAINT_94 PRIMARY KEY(DB_ID);
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.PHASING_POLL_RESULT;
CREATE UNIQUE INDEX PUBLIC.PHASING_POLL_RESULT_ID_IDX ON PUBLIC.PHASING_POLL_RESULT(ID);
CREATE INDEX PUBLIC.PHASING_POLL_RESULT_HEIGHT_IDX ON PUBLIC.PHASING_POLL_RESULT(HEIGHT);
CREATE CACHED TABLE PUBLIC.ACCOUNT_INFO(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_FC56E1E9_7904_4931_BCFD_6A555F4F82FC) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_FC56E1E9_7904_4931_BCFD_6A555F4F82FC SELECTIVITY 100,
ACCOUNT_ID BIGINT NOT NULL SELECTIVITY 100,
NAME VARCHAR SELECTIVITY 100,
DESCRIPTION VARCHAR SELECTIVITY 8,
HEIGHT INT NOT NULL SELECTIVITY 100,
LATEST BOOLEAN DEFAULT TRUE NOT NULL SELECTIVITY 8
);
ALTER TABLE PUBLIC.ACCOUNT_INFO ADD CONSTRAINT PUBLIC.CONSTRAINT_CC PRIMARY KEY(DB_ID);
-- 26 +/- SELECT COUNT(*) FROM PUBLIC.ACCOUNT_INFO;
CREATE UNIQUE INDEX PUBLIC.ACCOUNT_INFO_ID_HEIGHT_IDX ON PUBLIC.ACCOUNT_INFO(ACCOUNT_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.ACCOUNT_INFO_HEIGHT_ID_IDX ON PUBLIC.ACCOUNT_INFO(HEIGHT, ACCOUNT_ID);
CREATE CACHED TABLE PUBLIC.PRUNABLE_MESSAGE(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_0ECC3693_53EF_4260_87EE_462587450E46) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_0ECC3693_53EF_4260_87EE_462587450E46,
ID BIGINT NOT NULL,
SENDER_ID BIGINT NOT NULL,
RECIPIENT_ID BIGINT,
MESSAGE VARBINARY,
MESSAGE_IS_TEXT BOOLEAN NOT NULL,
IS_COMPRESSED BOOLEAN NOT NULL,
ENCRYPTED_MESSAGE VARBINARY,
ENCRYPTED_IS_TEXT BOOLEAN DEFAULT FALSE,
BLOCK_TIMESTAMP INT NOT NULL,
TRANSACTION_TIMESTAMP INT NOT NULL,
HEIGHT INT NOT NULL
);
ALTER TABLE PUBLIC.PRUNABLE_MESSAGE ADD CONSTRAINT PUBLIC.CONSTRAINT_B4 PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PRUNABLE_MESSAGE;
CREATE UNIQUE INDEX PUBLIC.PRUNABLE_MESSAGE_ID_IDX ON PUBLIC.PRUNABLE_MESSAGE(ID);
CREATE INDEX PUBLIC.PRUNABLE_MESSAGE_TRANSACTION_TIMESTAMP_IDX ON PUBLIC.PRUNABLE_MESSAGE(TRANSACTION_TIMESTAMP DESC);
CREATE INDEX PUBLIC.PRUNABLE_MESSAGE_SENDER_IDX ON PUBLIC.PRUNABLE_MESSAGE(SENDER_ID);
CREATE INDEX PUBLIC.PRUNABLE_MESSAGE_RECIPIENT_IDX ON PUBLIC.PRUNABLE_MESSAGE(RECIPIENT_ID);
CREATE INDEX PUBLIC.PRUNABLE_MESSAGE_BLOCK_TIMESTAMP_DBID_IDX ON PUBLIC.PRUNABLE_MESSAGE(BLOCK_TIMESTAMP DESC, DB_ID DESC);
CREATE CACHED TABLE PUBLIC.TAGGED_DATA(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_4248AF3C_35F7_4E97_A4D3_2FCC738DD4F7) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_4248AF3C_35F7_4E97_A4D3_2FCC738DD4F7,
ID BIGINT NOT NULL,
ACCOUNT_ID BIGINT NOT NULL,
NAME VARCHAR NOT NULL,
DESCRIPTION VARCHAR,
TAGS VARCHAR,
PARSED_TAGS ARRAY,
TYPE VARCHAR,
DATA VARBINARY NOT NULL,
IS_TEXT BOOLEAN NOT NULL,
CHANNEL VARCHAR,
FILENAME VARCHAR,
BLOCK_TIMESTAMP INT NOT NULL,
TRANSACTION_TIMESTAMP INT NOT NULL,
HEIGHT INT NOT NULL,
LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
ALTER TABLE PUBLIC.TAGGED_DATA ADD CONSTRAINT PUBLIC.CONSTRAINT_8B PRIMARY KEY(DB_ID);
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.TAGGED_DATA;
CREATE UNIQUE INDEX PUBLIC.TAGGED_DATA_ID_HEIGHT_IDX ON PUBLIC.TAGGED_DATA(ID, HEIGHT DESC);
CREATE INDEX PUBLIC.TAGGED_DATA_EXPIRATION_IDX ON PUBLIC.TAGGED_DATA(TRANSACTION_TIMESTAMP DESC);
CREATE INDEX PUBLIC.TAGGED_DATA_ACCOUNT_ID_HEIGHT_IDX ON PUBLIC.TAGGED_DATA(ACCOUNT_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.TAGGED_DATA_BLOCK_TIMESTAMP_HEIGHT_DB_ID_IDX ON PUBLIC.TAGGED_DATA(BLOCK_TIMESTAMP DESC, HEIGHT DESC, DB_ID DESC);
CREATE INDEX PUBLIC.TAGGED_DATA_CHANNEL_IDX ON PUBLIC.TAGGED_DATA(CHANNEL, HEIGHT DESC);
CREATE CACHED TABLE PUBLIC.DATA_TAG(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_6BE1A667_76F2_422B_AFB2_E87365DA6A28) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_6BE1A667_76F2_422B_AFB2_E87365DA6A28,
TAG VARCHAR NOT NULL,
TAG_COUNT INT NOT NULL,
HEIGHT INT NOT NULL,
LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
ALTER TABLE PUBLIC.DATA_TAG ADD CONSTRAINT PUBLIC.CONSTRAINT_99 PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DATA_TAG;
CREATE UNIQUE INDEX PUBLIC.DATA_TAG_TAG_HEIGHT_IDX ON PUBLIC.DATA_TAG(TAG, HEIGHT DESC);
CREATE INDEX PUBLIC.DATA_TAG_COUNT_HEIGHT_IDX ON PUBLIC.DATA_TAG(TAG_COUNT DESC, HEIGHT DESC);
CREATE CACHED TABLE PUBLIC.TAGGED_DATA_TIMESTAMP(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_81A85DFB_F28B_4884_9338_290DDA3DFE7B) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_81A85DFB_F28B_4884_9338_290DDA3DFE7B,
ID BIGINT NOT NULL,
TIMESTAMP INT NOT NULL,
HEIGHT INT NOT NULL,
LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
ALTER TABLE PUBLIC.TAGGED_DATA_TIMESTAMP ADD CONSTRAINT PUBLIC.CONSTRAINT_B5 PRIMARY KEY(DB_ID);
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.TAGGED_DATA_TIMESTAMP;
CREATE UNIQUE INDEX PUBLIC.TAGGED_DATA_TIMESTAMP_ID_HEIGHT_IDX ON PUBLIC.TAGGED_DATA_TIMESTAMP(ID, HEIGHT DESC);
CREATE INDEX PUBLIC.TAGGED_DATA_TIMESTAMP_HEIGHT_ID_IDX ON PUBLIC.TAGGED_DATA_TIMESTAMP(HEIGHT, ID);
CREATE CACHED TABLE PUBLIC.ACCOUNT_LEASE(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_EAC05067_4987_4D7F_A42B_1A2135E7038C) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_EAC05067_4987_4D7F_A42B_1A2135E7038C,
LESSOR_ID BIGINT NOT NULL,
CURRENT_LEASING_HEIGHT_FROM INT,
CURRENT_LEASING_HEIGHT_TO INT,
CURRENT_LESSEE_ID BIGINT,
NEXT_LEASING_HEIGHT_FROM INT,
NEXT_LEASING_HEIGHT_TO INT,
NEXT_LESSEE_ID BIGINT,
HEIGHT INT NOT NULL,
LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
ALTER TABLE PUBLIC.ACCOUNT_LEASE ADD CONSTRAINT PUBLIC.CONSTRAINT_D PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ACCOUNT_LEASE;
CREATE UNIQUE INDEX PUBLIC.ACCOUNT_LEASE_LESSOR_ID_HEIGHT_IDX ON PUBLIC.ACCOUNT_LEASE(LESSOR_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.ACCOUNT_LEASE_CURRENT_LEASING_HEIGHT_FROM_IDX ON PUBLIC.ACCOUNT_LEASE(CURRENT_LEASING_HEIGHT_FROM);
CREATE INDEX PUBLIC.ACCOUNT_LEASE_CURRENT_LEASING_HEIGHT_TO_IDX ON PUBLIC.ACCOUNT_LEASE(CURRENT_LEASING_HEIGHT_TO);
CREATE INDEX PUBLIC.ACCOUNT_LEASE_HEIGHT_ID_IDX ON PUBLIC.ACCOUNT_LEASE(HEIGHT, LESSOR_ID);
CREATE CACHED TABLE PUBLIC.EXCHANGE_REQUEST(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_FB8293B0_4068_471F_8AA7_9F99DE361C91) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_FB8293B0_4068_471F_8AA7_9F99DE361C91,
ID BIGINT NOT NULL,
ACCOUNT_ID BIGINT NOT NULL,
CURRENCY_ID BIGINT NOT NULL,
UNITS BIGINT NOT NULL,
RATE BIGINT NOT NULL,
IS_BUY BOOLEAN NOT NULL,
TIMESTAMP INT NOT NULL,
HEIGHT INT NOT NULL
);
ALTER TABLE PUBLIC.EXCHANGE_REQUEST ADD CONSTRAINT PUBLIC.CONSTRAINT_E2 PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.EXCHANGE_REQUEST;
CREATE UNIQUE INDEX PUBLIC.EXCHANGE_REQUEST_ID_IDX ON PUBLIC.EXCHANGE_REQUEST(ID);
CREATE INDEX PUBLIC.EXCHANGE_REQUEST_ACCOUNT_CURRENCY_IDX ON PUBLIC.EXCHANGE_REQUEST(ACCOUNT_ID, CURRENCY_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.EXCHANGE_REQUEST_CURRENCY_IDX ON PUBLIC.EXCHANGE_REQUEST(CURRENCY_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.EXCHANGE_REQUEST_HEIGHT_DB_ID_IDX ON PUBLIC.EXCHANGE_REQUEST(HEIGHT DESC, DB_ID DESC);
CREATE INDEX PUBLIC.EXCHANGE_REQUEST_HEIGHT_IDX ON PUBLIC.EXCHANGE_REQUEST(HEIGHT);
CREATE CACHED TABLE PUBLIC.ACCOUNT_LEDGER(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_51DABEF2_E173_4EF3_8D33_3D5F38711C92) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_51DABEF2_E173_4EF3_8D33_3D5F38711C92 SELECTIVITY 100,
ACCOUNT_ID BIGINT NOT NULL SELECTIVITY 1,
EVENT_TYPE TINYINT NOT NULL SELECTIVITY 1,
EVENT_ID BIGINT NOT NULL SELECTIVITY 37,
HOLDING_TYPE TINYINT NOT NULL SELECTIVITY 1,
HOLDING_ID BIGINT SELECTIVITY 1,
CHANGE BIGINT NOT NULL SELECTIVITY 6,
BALANCE BIGINT NOT NULL SELECTIVITY 95,
BLOCK_ID BIGINT NOT NULL SELECTIVITY 6,
HEIGHT INT NOT NULL SELECTIVITY 6,
TIMESTAMP INT NOT NULL SELECTIVITY 6
);
ALTER TABLE PUBLIC.ACCOUNT_LEDGER ADD CONSTRAINT PUBLIC.CONSTRAINT_41 PRIMARY KEY(DB_ID);
-- 1444 +/- SELECT COUNT(*) FROM PUBLIC.ACCOUNT_LEDGER;
CREATE INDEX PUBLIC.ACCOUNT_LEDGER_ID_IDX ON PUBLIC.ACCOUNT_LEDGER(ACCOUNT_ID, DB_ID);
CREATE INDEX PUBLIC.ACCOUNT_LEDGER_HEIGHT_IDX ON PUBLIC.ACCOUNT_LEDGER(HEIGHT);
CREATE CACHED TABLE PUBLIC.TAGGED_DATA_EXTEND(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_B0838F08_B2A0_4ACC_B64D_7A8DBF112E8D) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_B0838F08_B2A0_4ACC_B64D_7A8DBF112E8D,
ID BIGINT NOT NULL,
EXTEND_ID BIGINT NOT NULL,
HEIGHT INT NOT NULL,
LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
ALTER TABLE PUBLIC.TAGGED_DATA_EXTEND ADD CONSTRAINT PUBLIC.CONSTRAINT_43 PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TAGGED_DATA_EXTEND;
CREATE INDEX PUBLIC.TAGGED_DATA_EXTEND_ID_HEIGHT_IDX ON PUBLIC.TAGGED_DATA_EXTEND(ID, HEIGHT DESC);
CREATE INDEX PUBLIC.TAGGED_DATA_EXTEND_HEIGHT_ID_IDX ON PUBLIC.TAGGED_DATA_EXTEND(HEIGHT, ID);
CREATE CACHED TABLE FTL.INDEXES(
SCHEMA VARCHAR NOT NULL SELECTIVITY 16,
TABLE VARCHAR NOT NULL SELECTIVITY 100,
COLUMNS VARCHAR SELECTIVITY 50
);
ALTER TABLE FTL.INDEXES ADD CONSTRAINT FTL.CONSTRAINT_9 PRIMARY KEY(SCHEMA, TABLE);
-- 6 +/- SELECT COUNT(*) FROM FTL.INDEXES;
CREATE CACHED TABLE PUBLIC.SHUFFLING(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_9B3AE74B_E66D_4B93_84D5_1EF01A057E26) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_9B3AE74B_E66D_4B93_84D5_1EF01A057E26,
ID BIGINT NOT NULL,
HOLDING_ID BIGINT,
HOLDING_TYPE TINYINT NOT NULL,
ISSUER_ID BIGINT NOT NULL,
AMOUNT BIGINT NOT NULL,
PARTICIPANT_COUNT TINYINT NOT NULL,
BLOCKS_REMAINING SMALLINT,
STAGE TINYINT NOT NULL,
ASSIGNEE_ACCOUNT_ID BIGINT,
REGISTRANT_COUNT TINYINT NOT NULL,
RECIPIENT_PUBLIC_KEYS ARRAY,
HEIGHT INT NOT NULL,
LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
ALTER TABLE PUBLIC.SHUFFLING ADD CONSTRAINT PUBLIC.CONSTRAINT_55 PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SHUFFLING;
CREATE UNIQUE INDEX PUBLIC.SHUFFLING_ID_HEIGHT_IDX ON PUBLIC.SHUFFLING(ID, HEIGHT DESC);
CREATE INDEX PUBLIC.SHUFFLING_HOLDING_ID_HEIGHT_IDX ON PUBLIC.SHUFFLING(HOLDING_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.SHUFFLING_ASSIGNEE_ACCOUNT_ID_HEIGHT_IDX ON PUBLIC.SHUFFLING(ASSIGNEE_ACCOUNT_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.SHUFFLING_HEIGHT_ID_IDX ON PUBLIC.SHUFFLING(HEIGHT, ID);
CREATE INDEX PUBLIC.SHUFFLING_BLOCKS_REMAINING_HEIGHT_IDX ON PUBLIC.SHUFFLING(BLOCKS_REMAINING, HEIGHT DESC);
CREATE CACHED TABLE PUBLIC.SHUFFLING_PARTICIPANT(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_22A879DE_118B_43ED_8BF0_A4D9E0E8361F) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_22A879DE_118B_43ED_8BF0_A4D9E0E8361F,
SHUFFLING_ID BIGINT NOT NULL,
ACCOUNT_ID BIGINT NOT NULL,
NEXT_ACCOUNT_ID BIGINT,
PARTICIPANT_INDEX TINYINT NOT NULL,
STATE TINYINT NOT NULL,
BLAME_DATA ARRAY,
KEY_SEEDS ARRAY,
DATA_TRANSACTION_FULL_HASH BINARY(32),
HEIGHT INT NOT NULL,
LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
ALTER TABLE PUBLIC.SHUFFLING_PARTICIPANT ADD CONSTRAINT PUBLIC.CONSTRAINT_6 PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SHUFFLING_PARTICIPANT;
CREATE UNIQUE INDEX PUBLIC.SHUFFLING_PARTICIPANT_SHUFFLING_ID_ACCOUNT_ID_IDX ON PUBLIC.SHUFFLING_PARTICIPANT(SHUFFLING_ID, ACCOUNT_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.SHUFFLING_PARTICIPANT_HEIGHT_IDX ON PUBLIC.SHUFFLING_PARTICIPANT(HEIGHT, SHUFFLING_ID, ACCOUNT_ID);
CREATE CACHED TABLE PUBLIC.SHUFFLING_DATA(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_C670A685_58B2_49C2_8E4C_C6D4F10AE4CD) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_C670A685_58B2_49C2_8E4C_C6D4F10AE4CD,
SHUFFLING_ID BIGINT NOT NULL,
ACCOUNT_ID BIGINT NOT NULL,
DATA ARRAY,
TRANSACTION_TIMESTAMP INT NOT NULL,
HEIGHT INT NOT NULL
);
ALTER TABLE PUBLIC.SHUFFLING_DATA ADD CONSTRAINT PUBLIC.CONSTRAINT_A0 PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SHUFFLING_DATA;
CREATE UNIQUE INDEX PUBLIC.SHUFFLING_DATA_ID_HEIGHT_IDX ON PUBLIC.SHUFFLING_DATA(SHUFFLING_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.SHUFFLING_DATA_TRANSACTION_TIMESTAMP_IDX ON PUBLIC.SHUFFLING_DATA(TRANSACTION_TIMESTAMP DESC);
CREATE CACHED TABLE PUBLIC.PHASING_POLL_LINKED_TRANSACTION(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_7DAE5796_5D08_4878_B93A_26EABA14BEEA) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_7DAE5796_5D08_4878_B93A_26EABA14BEEA,
TRANSACTION_ID BIGINT NOT NULL,
LINKED_FULL_HASH BINARY(32) NOT NULL,
LINKED_TRANSACTION_ID BIGINT NOT NULL,
HEIGHT INT NOT NULL
);
ALTER TABLE PUBLIC.PHASING_POLL_LINKED_TRANSACTION ADD CONSTRAINT PUBLIC.CONSTRAINT_67 PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PHASING_POLL_LINKED_TRANSACTION;
CREATE UNIQUE INDEX PUBLIC.PHASING_POLL_LINKED_TRANSACTION_ID_LINK_IDX ON PUBLIC.PHASING_POLL_LINKED_TRANSACTION(TRANSACTION_ID, LINKED_TRANSACTION_ID);
CREATE INDEX PUBLIC.PHASING_POLL_LINKED_TRANSACTION_HEIGHT_IDX ON PUBLIC.PHASING_POLL_LINKED_TRANSACTION(HEIGHT);
CREATE UNIQUE INDEX PUBLIC.PHASING_POLL_LINKED_TRANSACTION_LINK_ID_IDX ON PUBLIC.PHASING_POLL_LINKED_TRANSACTION(LINKED_TRANSACTION_ID, TRANSACTION_ID);
CREATE CACHED TABLE PUBLIC.ACCOUNT_CONTROL_PHASING(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_03B94F82_FD80_4D84_8CF0_A6F28DCD9CF1) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_03B94F82_FD80_4D84_8CF0_A6F28DCD9CF1,
ACCOUNT_ID BIGINT NOT NULL,
WHITELIST ARRAY,
VOTING_MODEL TINYINT NOT NULL,
QUORUM BIGINT,
MIN_BALANCE BIGINT,
HOLDING_ID BIGINT,
MIN_BALANCE_MODEL TINYINT,
MAX_FEES BIGINT,
MIN_DURATION SMALLINT,
MAX_DURATION SMALLINT,
HEIGHT INT NOT NULL,
LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
ALTER TABLE PUBLIC.ACCOUNT_CONTROL_PHASING ADD CONSTRAINT PUBLIC.CONSTRAINT_42 PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ACCOUNT_CONTROL_PHASING;
CREATE UNIQUE INDEX PUBLIC.ACCOUNT_CONTROL_PHASING_ID_HEIGHT_IDX ON PUBLIC.ACCOUNT_CONTROL_PHASING(ACCOUNT_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.ACCOUNT_CONTROL_PHASING_HEIGHT_ID_IDX ON PUBLIC.ACCOUNT_CONTROL_PHASING(HEIGHT, ACCOUNT_ID);
CREATE CACHED TABLE PUBLIC.ACCOUNT_PROPERTY(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_719D675E_E14D_4B7E_9EE7_F7783292A612) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_719D675E_E14D_4B7E_9EE7_F7783292A612,
ID BIGINT NOT NULL,
RECIPIENT_ID BIGINT NOT NULL,
SETTER_ID BIGINT,
PROPERTY VARCHAR NOT NULL,
VALUE VARCHAR,
HEIGHT INT NOT NULL,
LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
CREATE CACHED TABLE PUBLIC.TWO_FACTOR_AUTH (
            account BIGINT PRIMARY KEY,
            secret VARBINARY,
            confirmed BOOLEAN
            );
ALTER TABLE PUBLIC.ACCOUNT_PROPERTY ADD CONSTRAINT PUBLIC.CONSTRAINT_8E8D PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ACCOUNT_PROPERTY;
CREATE UNIQUE INDEX PUBLIC.ACCOUNT_PROPERTY_ID_HEIGHT_IDX ON PUBLIC.ACCOUNT_PROPERTY(ID, HEIGHT DESC);
CREATE INDEX PUBLIC.ACCOUNT_PROPERTY_HEIGHT_ID_IDX ON PUBLIC.ACCOUNT_PROPERTY(HEIGHT, ID);
CREATE INDEX PUBLIC.ACCOUNT_PROPERTY_RECIPIENT_HEIGHT_IDX ON PUBLIC.ACCOUNT_PROPERTY(RECIPIENT_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.ACCOUNT_PROPERTY_SETTER_RECIPIENT_IDX ON PUBLIC.ACCOUNT_PROPERTY(SETTER_ID, RECIPIENT_ID);
CREATE CACHED TABLE PUBLIC.ASSET_DELETE(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_2EE8C924_F2E6_40F5_BB7C_142ECF11E3B0) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_2EE8C924_F2E6_40F5_BB7C_142ECF11E3B0,
ID BIGINT NOT NULL,
ASSET_ID BIGINT NOT NULL,
ACCOUNT_ID BIGINT NOT NULL,
QUANTITY BIGINT NOT NULL,
TIMESTAMP INT NOT NULL,
HEIGHT INT NOT NULL
);
ALTER TABLE PUBLIC.ASSET_DELETE ADD CONSTRAINT PUBLIC.CONSTRAINT_93 PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ASSET_DELETE;
CREATE UNIQUE INDEX PUBLIC.ASSET_DELETE_ID_IDX ON PUBLIC.ASSET_DELETE(ID);
CREATE INDEX PUBLIC.ASSET_DELETE_ASSET_ID_IDX ON PUBLIC.ASSET_DELETE(ASSET_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.ASSET_DELETE_ACCOUNT_ID_IDX ON PUBLIC.ASSET_DELETE(ACCOUNT_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.ASSET_DELETE_HEIGHT_IDX ON PUBLIC.ASSET_DELETE(HEIGHT);
CREATE CACHED TABLE PUBLIC.REFERENCED_TRANSACTION(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_1700B4D9_DFA3_4995_9E87_D534E607A9B5) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_1700B4D9_DFA3_4995_9E87_D534E607A9B5,
TRANSACTION_ID BIGINT NOT NULL,
REFERENCED_TRANSACTION_ID BIGINT NOT NULL
);
ALTER TABLE PUBLIC.REFERENCED_TRANSACTION ADD CONSTRAINT PUBLIC.CONSTRAINT_4B PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.REFERENCED_TRANSACTION;
CREATE INDEX PUBLIC.REFERENCED_TRANSACTION_REFERENCED_TRANSACTION_ID_IDX ON PUBLIC.REFERENCED_TRANSACTION(REFERENCED_TRANSACTION_ID);
CREATE CACHED TABLE PUBLIC.ASSET_DIVIDEND(
DB_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_3F3CCF94_E2B9_497C_A7D7_86A88A541B23) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_3F3CCF94_E2B9_497C_A7D7_86A88A541B23,
ID BIGINT NOT NULL,
ASSET_ID BIGINT NOT NULL,
AMOUNT BIGINT NOT NULL,
DIVIDEND_HEIGHT INT NOT NULL,
TOTAL_DIVIDEND BIGINT NOT NULL,
NUM_ACCOUNTS BIGINT NOT NULL,
TIMESTAMP INT NOT NULL,
HEIGHT INT NOT NULL
);
ALTER TABLE PUBLIC.ASSET_DIVIDEND ADD CONSTRAINT PUBLIC.CONSTRAINT_BF PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ASSET_DIVIDEND;
CREATE UNIQUE INDEX PUBLIC.ASSET_DIVIDEND_ID_IDX ON PUBLIC.ASSET_DIVIDEND(ID);
CREATE INDEX PUBLIC.ASSET_DIVIDEND_ASSET_ID_IDX ON PUBLIC.ASSET_DIVIDEND(ASSET_ID, HEIGHT DESC);
CREATE INDEX PUBLIC.ASSET_DIVIDEND_HEIGHT_IDX ON PUBLIC.ASSET_DIVIDEND(HEIGHT);
CREATE CACHED TABLE PUBLIC.UPDATE_STATUS(
DB_ID BIGINT DEFAULT PUBLIC.update_status_seq.nextval NOT NULL,
TRANSACTION_ID BIGINT NOT NULL,
UPDATED BOOLEAN DEFAULT FALSE NOT NULL
);
ALTER TABLE PUBLIC.UPDATE_STATUS ADD CONSTRAINT PUBLIC.CONSTRAINT_66 PRIMARY KEY(DB_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.UPDATE_STATUS;
ALTER TABLE PUBLIC.PUBLIC_KEY ADD CONSTRAINT PUBLIC.CONSTRAINT_8E8 FOREIGN KEY(HEIGHT) REFERENCES PUBLIC.BLOCK(HEIGHT) ON DELETE CASCADE NOCHECK;
ALTER TABLE PUBLIC.PRUNABLE_MESSAGE ADD CONSTRAINT PUBLIC.CONSTRAINT_B40 FOREIGN KEY(HEIGHT) REFERENCES PUBLIC.BLOCK(HEIGHT) ON DELETE CASCADE NOCHECK;
ALTER TABLE PUBLIC.TRANSACTION ADD CONSTRAINT PUBLIC.CONSTRAINT_FF FOREIGN KEY(BLOCK_ID) REFERENCES PUBLIC.BLOCK(ID) ON DELETE CASCADE NOCHECK;
ALTER TABLE PUBLIC.DATA_TAG ADD CONSTRAINT PUBLIC.CONSTRAINT_995 FOREIGN KEY(HEIGHT) REFERENCES PUBLIC.BLOCK(HEIGHT) ON DELETE CASCADE NOCHECK;
ALTER TABLE PUBLIC.SHUFFLING_DATA ADD CONSTRAINT PUBLIC.CONSTRAINT_A08 FOREIGN KEY(HEIGHT) REFERENCES PUBLIC.BLOCK(HEIGHT) ON DELETE CASCADE NOCHECK;
ALTER TABLE PUBLIC.UPDATE_STATUS ADD CONSTRAINT PUBLIC.CONSTRAINT_660 FOREIGN KEY(TRANSACTION_ID) REFERENCES PUBLIC.TRANSACTION(ID) ON DELETE CASCADE NOCHECK;
ALTER TABLE PUBLIC.TAGGED_DATA ADD CONSTRAINT PUBLIC.CONSTRAINT_8B9 FOREIGN KEY(HEIGHT) REFERENCES PUBLIC.BLOCK(HEIGHT) ON DELETE CASCADE NOCHECK;
ALTER TABLE PUBLIC.REFERENCED_TRANSACTION ADD CONSTRAINT PUBLIC.CONSTRAINT_4B1 FOREIGN KEY(TRANSACTION_ID) REFERENCES PUBLIC.TRANSACTION(ID) ON DELETE CASCADE NOCHECK;
CREATE FORCE TRIGGER PUBLIC.FTL_CURRENCY AFTER INSERT, UPDATE, DELETE ON PUBLIC.CURRENCY FOR EACH ROW QUEUE 1024 CALL "com.apollocurrency.aplwallet.apl.db.FullTextTrigger";
CREATE FORCE TRIGGER PUBLIC.FTL_ACCOUNT_INFO AFTER INSERT, UPDATE, DELETE ON PUBLIC.ACCOUNT_INFO FOR EACH ROW QUEUE 1024 CALL "com.apollocurrency.aplwallet.apl.db.FullTextTrigger";
CREATE FORCE TRIGGER PUBLIC.FTL_TAGGED_DATA AFTER INSERT, UPDATE, DELETE ON PUBLIC.TAGGED_DATA FOR EACH ROW QUEUE 1024 CALL "com.apollocurrency.aplwallet.apl.db.FullTextTrigger";
CREATE FORCE TRIGGER PUBLIC.FTL_ASSET AFTER INSERT, UPDATE, DELETE ON PUBLIC.ASSET FOR EACH ROW QUEUE 1024 CALL "com.apollocurrency.aplwallet.apl.db.FullTextTrigger";
CREATE FORCE TRIGGER PUBLIC.FTL_GOODS AFTER INSERT, UPDATE, DELETE ON PUBLIC.GOODS FOR EACH ROW QUEUE 1024 CALL "com.apollocurrency.aplwallet.apl.db.FullTextTrigger";
CREATE FORCE TRIGGER PUBLIC.FTL_POLL AFTER INSERT, UPDATE, DELETE ON PUBLIC.POLL FOR EACH ROW QUEUE 1024 CALL "com.apollocurrency.aplwallet.apl.db.FullTextTrigger";
