SET MAX_MEMORY_ROWS 1000000;
SET CACHE_SIZE 262144;
SET DEFAULT_LOCK_TIMEOUT 60000;

CREATE FORCE TRIGGER IF NOT EXISTS PUBLIC.FTL_CURRENCY AFTER INSERT, UPDATE, DELETE ON PUBLIC.CURRENCY FOR EACH ROW QUEUE 1024 CALL "com.apollocurrency.aplwallet.apl.db.FullTextTrigger";
CREATE FORCE TRIGGER IF NOT EXISTS PUBLIC.FTL_ACCOUNT_INFO AFTER INSERT, UPDATE, DELETE ON PUBLIC.ACCOUNT_INFO FOR EACH ROW QUEUE 1024 CALL "com.apollocurrency.aplwallet.apl.db.FullTextTrigger";
CREATE FORCE TRIGGER IF NOT EXISTS PUBLIC.FTL_TAGGED_DATA AFTER INSERT, UPDATE, DELETE ON PUBLIC.TAGGED_DATA FOR EACH ROW QUEUE 1024 CALL "com.apollocurrency.aplwallet.apl.db.FullTextTrigger";
CREATE FORCE TRIGGER IF NOT EXISTS PUBLIC.FTL_ASSET AFTER INSERT, UPDATE, DELETE ON PUBLIC.ASSET FOR EACH ROW QUEUE 1024 CALL "com.apollocurrency.aplwallet.apl.db.FullTextTrigger";
CREATE FORCE TRIGGER IF NOT EXISTS PUBLIC.FTL_GOODS AFTER INSERT, UPDATE, DELETE ON PUBLIC.GOODS FOR EACH ROW QUEUE 1024 CALL "com.apollocurrency.aplwallet.apl.db.FullTextTrigger";
CREATE FORCE TRIGGER IF NOT EXISTS PUBLIC.FTL_POLL AFTER INSERT, UPDATE, DELETE ON PUBLIC.POLL FOR EACH ROW QUEUE 1024 CALL "com.apollocurrency.aplwallet.apl.db.FullTextTrigger";
CREATE SCHEMA IF NOT EXISTS FTL;
CREATE TABLE IF NOT EXISTS FTL.INDEXES(SCHEMA VARCHAR, TABLE VARCHAR, COLUMNS VARCHAR, PRIMARY KEY(SCHEMA, TABLE));